"""1

Revision ID: 4156c7366167
Revises: 9b99d94336f7
Create Date: 2026-02-22 00:34:27.694755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4156c7366167'
down_revision: Union[str, Sequence[str], None] = '9b99d94336f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('missions', sa.Column('team_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('missions_ibfk_1'), 'missions', type_='foreignkey')
    op.create_foreign_key(None, 'missions', 'teams', ['team_id'], ['id'])
    op.drop_column('missions', 'group_id')
    op.drop_column('missions', 'status')
    op.drop_column('missions', 'decided_by_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('decided_by_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('missions', sa.Column('status', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('missions', sa.Column('group_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'missions', type_='foreignkey')
    op.create_foreign_key(op.f('missions_ibfk_1'), 'missions', 'groups', ['group_id'], ['id'])
    op.drop_column('missions', 'team_id')
    op.drop_table('group_missions')
    # ### end Alembic commands ###
