"""1

Revision ID: 9b99d94336f7
Revises: fa936100175b
Create Date: 2026-02-22 00:19:03.160808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b99d94336f7'
down_revision: Union[str, Sequence[str], None] = 'fa936100175b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('username'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###
